import * as admin from "firebase-admin";
import {FieldValue, getFirestore} from "firebase-admin/firestore";
import {HttpsError, onCall} from "firebase-functions/v2/https";
import {requireAdminPermission} from "../admin/adminAuthorizationService";
import {writeAdminAuditLog} from "../admin/adminAuditLogService";
import {getOrderDeliveryPolicy, ORDER_DELIVERY_POLICY_DOCUMENT, parseOrderDeliveryPolicy} from "../admin/orderDeliveryPolicy";
if (admin.apps.length === 0) admin.initializeApp();
const db = getFirestore("default");
function record(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function valid(value: Record<string, unknown>): boolean { const intervals = record(value.reminderIntervalsMinutes); const scheduling = record(value.scheduling); return typeof value.minutesPerMile === "number" && Number.isInteger(value.minutesPerMile) && value.minutesPerMile >= 1 && value.minutesPerMile <= 60 && typeof value.defaultPreparationMinutes === "number" && Number.isInteger(value.defaultPreparationMinutes) && value.defaultPreparationMinutes >= 0 && value.defaultPreparationMinutes <= 180 && [intervals.pending, intervals.accepted, intervals.preparing].every((item) => typeof item === "number" && Number.isInteger(item) && item >= 5 && item <= 1440) && typeof scheduling.pickupEnabled === "boolean" && typeof scheduling.deliveryEnabled === "boolean" && Number.isInteger(scheduling.maximumDaysAhead) && Number(scheduling.maximumDaysAhead) >= 1 && Number(scheduling.maximumDaysAhead) <= 30 && Number.isInteger(scheduling.slotIntervalMinutes) && Number(scheduling.slotIntervalMinutes) >= 15 && Number(scheduling.slotIntervalMinutes) <= 120 && Number.isInteger(scheduling.defaultOrdersPerSlot) && Number(scheduling.defaultOrdersPerSlot) >= 1 && Number(scheduling.defaultOrdersPerSlot) <= 100; }
export const getAdminOrderDeliveryPolicy = onCall({region: "us-central1"}, async (request) => { await requireAdminPermission(request, "settings"); return {policy: await getOrderDeliveryPolicy()}; });
export const getOrderDeliveryPolicyForClient = onCall({region: "us-central1"}, async (request) => { if (!request.auth) throw new HttpsError("unauthenticated", "Sign in to load delivery estimates."); return {policy: await getOrderDeliveryPolicy()}; });
export const saveAdminOrderDeliveryPolicy = onCall({region: "us-central1"}, async (request) => { const administrator = await requireAdminPermission(request, "settings", "write"); const input = record(record(request.data).policy); if (!valid(input)) throw new HttpsError("invalid-argument", "Provide valid order and delivery policy values."); const policy = parseOrderDeliveryPolicy(input); await db.collection("settings").doc(ORDER_DELIVERY_POLICY_DOCUMENT).set({...policy, updatedAt: FieldValue.serverTimestamp(), updatedBy: administrator.uid}, {merge: true}); await writeAdminAuditLog(administrator, {action: "order_delivery_policy_updated", targetType: "settings", targetId: ORDER_DELIVERY_POLICY_DOCUMENT, details: {minutesPerMile: policy.minutesPerMile, defaultPreparationMinutes: policy.defaultPreparationMinutes, pendingReminderMinutes: policy.reminderIntervalsMinutes.pending, acceptedReminderMinutes: policy.reminderIntervalsMinutes.accepted, preparingReminderMinutes: policy.reminderIntervalsMinutes.preparing, scheduledPickupEnabled: policy.scheduling.pickupEnabled, scheduledDeliveryEnabled: policy.scheduling.deliveryEnabled, maximumDaysAhead: policy.scheduling.maximumDaysAhead, slotIntervalMinutes: policy.scheduling.slotIntervalMinutes, defaultOrdersPerSlot: policy.scheduling.defaultOrdersPerSlot}}); return {success: true}; });
