"use client";
import {useCallback, useEffect, useRef, useState} from "react";
import {Headphones, LoaderCircle, RefreshCw, Send, StickyNote} from "lucide-react";
import {useSearchParams} from "next/navigation";
import {useAdminAccess} from "@/context/AdminAccessContext";
import {accountSupportClientService, type AccountSupportMessage, type AccountSupportRequest} from "@/services/support/accountSupportClientService";

const label = (value: string) => value.replace(/_/g, " ");
const date = (value: string | null) => value ? new Date(value).toLocaleString("en-US", {dateStyle: "medium", timeStyle: "short"}) : "Pending timestamp";

export function AdminSupportWorkspace() {
  const params = useSearchParams(); const {canWrite} = useAdminAccess(); const writable = canWrite("support");
  const [requests, setRequests] = useState<AccountSupportRequest[]>([]); const [selectedId, setSelectedId] = useState(params.get("request") ?? ""); const [messages, setMessages] = useState<AccountSupportMessage[]>([]);
  const [filter, setFilter] = useState("all"); const [nextCursor, setNextCursor] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [assignees, setAssignees] = useState<Array<{uid: string; name: string; email: string}>>([]);
  const [message, setMessage] = useState(""); const [note, setNote] = useState(""); const [status, setStatus] = useState<"in_review" | "responded" | "resolved">("responded");
  const listLoadedRef = useRef(false); const loadingMoreRef = useRef(false); const requestSequenceRef = useRef(0);
  const load = useCallback(async (cursor?: string) => { if (cursor && loadingMoreRef.current) return; const requestSequence = cursor ? requestSequenceRef.current : ++requestSequenceRef.current; try { if (cursor) loadingMoreRef.current = true; else if (!listLoadedRef.current) setLoading(true); setError(""); const result = await accountSupportClientService.listAdmin(filter, cursor); if (!cursor && requestSequence !== requestSequenceRef.current) return; setRequests((current) => cursor ? [...current, ...result.requests] : result.requests); setNextCursor(result.nextCursor); setSelectedId((current) => cursor || result.requests.some((item) => item.id === current) ? current : result.requests[0]?.id || ""); listLoadedRef.current = true; } catch (reason) { if (requestSequence === requestSequenceRef.current) setError(reason instanceof Error ? reason.message : "Unable to load support requests."); } finally { setLoading(false); loadingMoreRef.current = false; } }, [filter]);
  const loadConversation = useCallback(async (id: string) => { try { const result = await accountSupportClientService.getConversation(id); setMessages(result.messages); setRequests((current) => current.map((item) => item.id === id ? result.request : item)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load the conversation."); } }, []);
  useEffect(() => { queueMicrotask(() => { void load(); void accountSupportClientService.getAssignees().then((result) => setAssignees(result.assignees)).catch(() => undefined); }); }, [load]);
  useEffect(() => { queueMicrotask(() => { if (selectedId) void loadConversation(selectedId); else setMessages([]); }); }, [loadConversation, selectedId]);
  const selected = requests.find((item) => item.id === selectedId) ?? null;
  const mutate = async (operation: () => Promise<unknown>) => { if (!selected) return; try { setBusy(true); setError(""); await operation(); await Promise.all([load(), loadConversation(selected.id)]); } catch (reason) { setError(reason instanceof Error ? reason.message : "The support request could not be updated."); } finally { setBusy(false); } };
  const respond = () => mutate(async () => { await accountSupportClientService.respondAdmin({requestId: selected!.id, message: message.trim(), status}); setMessage(""); });
  const addNote = () => mutate(async () => { await accountSupportClientService.addInternalNote(selected!.id, note.trim()); setNote(""); });
  const assign = (assigneeId: string) => mutate(() => accountSupportClientService.assignAdmin(selected!.id, assigneeId));
  return <section><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-black text-orange-600">LIA SUPPORT</p><h1 className="mt-1 text-3xl font-black">Support conversations</h1><p className="mt-2 text-sm text-slate-500">Assign ownership, preserve the complete conversation, and keep internal notes private.</p></div><button data-admin-read-action type="button" onClick={() => void load()} className="inline-flex items-center gap-2 rounded-full border bg-white px-4 py-2 text-sm font-bold"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`}/>Refresh</button></div>
    <div className="mt-6 flex gap-2 overflow-x-auto">{["all", "open", "in_review", "responded", "resolved"].map((value) => <button data-admin-read-action key={value} type="button" onClick={() => setFilter(value)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-bold capitalize ${filter === value ? "bg-orange-600 text-white" : "bg-white ring-1 ring-slate-200"}`}>{label(value)}</button>)}</div>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {loading && requests.length === 0 ? <div className="mt-10 flex justify-center"><LoaderCircle className="h-7 w-7 animate-spin text-orange-600"/></div> : requests.length === 0 ? <div className="mt-8 rounded-xl border bg-white p-10 text-center"><Headphones className="mx-auto h-8 w-8 text-slate-400"/><p className="mt-3 font-bold">No support requests</p></div> : <div className="mt-6 grid gap-5 lg:grid-cols-[340px_1fr]"><div className="space-y-2">{requests.map((item) => <button data-admin-read-action key={item.id} type="button" onClick={() => setSelectedId(item.id)} className={`w-full rounded-xl border p-4 text-left ${selectedId === item.id ? "border-orange-300 bg-orange-50" : "border-slate-200 bg-white"}`}><div className="flex justify-between gap-2"><p className="font-bold">{item.ownerName}</p><span className="text-xs font-bold capitalize text-slate-500">{label(item.status)}</span></div><p className="mt-1 text-xs font-semibold uppercase text-orange-700">{item.ownerType} · {label(item.reason)}</p><p className="mt-2 line-clamp-2 text-sm text-slate-600">{item.message}</p>{item.assignedTo && <p className="mt-2 text-xs font-bold text-blue-700">Assigned to {item.assignedTo.name || item.assignedTo.email}</p>}</button>)}{nextCursor && <button data-admin-read-action type="button" disabled={loading} onClick={() => void load(nextCursor)} className="w-full rounded-full border bg-white px-4 py-2 text-sm font-bold">Load more</button>}</div>
      {selected && <article className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black">{selected.ownerName}</h2><p className="mt-1 text-sm text-slate-500">{selected.ownerEmail} · {selected.ownerType}</p></div>{writable && <select aria-label="Assigned administrator" disabled={busy} value={selected.assignedTo?.uid ?? ""} onChange={(event) => void assign(event.target.value)} className="rounded-xl border bg-white px-3 py-2 text-xs font-bold"><option value="">Unassigned</option>{assignees.map((assignee) => <option key={assignee.uid} value={assignee.uid}>{assignee.name || assignee.email}</option>)}</select>}</div><div className="mt-5 max-h-[430px] space-y-3 overflow-y-auto rounded-xl bg-slate-50 p-4">{messages.map((entry) => <div key={entry.id} className={`rounded-xl p-3 ${entry.visibility === "internal" ? "border border-amber-200 bg-amber-50" : entry.senderType === "admin" ? "ml-5 bg-orange-100" : "mr-5 bg-white"}`}><div className="flex justify-between gap-3"><p className="text-xs font-black">{entry.visibility === "internal" ? "INTERNAL NOTE" : entry.senderName || entry.senderType}</p><p className="text-[11px] text-slate-500">{date(entry.createdAt)}</p></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{entry.message}</p></div>)}</div>
        {writable ? <div className="mt-5 grid gap-4"><label className="text-sm font-bold">Customer-visible response<textarea rows={4} value={message} onChange={(event) => setMessage(event.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal"/></label><div className="flex flex-wrap gap-2"><select value={status} onChange={(event) => setStatus(event.target.value as typeof status)} className="rounded-xl border bg-white px-3 py-2 text-sm font-bold"><option value="in_review">In review</option><option value="responded">Responded</option><option value="resolved">Resolved</option></select><button type="button" disabled={busy || message.trim().length < 2} onClick={() => void respond()} className="inline-flex items-center gap-2 rounded-full bg-orange-600 px-5 py-2 text-sm font-bold text-white disabled:opacity-50"><Send className="h-4 w-4"/>Send response</button></div><label className="text-sm font-bold">Private internal note<textarea rows={3} value={note} onChange={(event) => setNote(event.target.value)} className="mt-2 w-full rounded-xl border border-amber-200 bg-amber-50 p-3 font-normal"/></label><button type="button" disabled={busy || note.trim().length < 2} onClick={() => void addNote()} className="inline-flex w-fit items-center gap-2 rounded-full bg-slate-900 px-5 py-2 text-sm font-bold text-white disabled:opacity-50"><StickyNote className="h-4 w-4"/>Add internal note</button></div> : <p className="mt-5 rounded-xl bg-blue-50 p-3 text-sm text-blue-800">Read-only access: conversation changes are disabled.</p>}</article>}</div>}
  </section>;
}
