"use client";
/* eslint-disable react-hooks/set-state-in-effect -- protected settings loaders initialize independent policy editors */
import {useEffect, useState} from "react";
import {ArrowLeft, Bell, Building2, CircleDollarSign, ClipboardCheck, DatabaseZap, History, LoaderCircle, PackageCheck, ShieldCheck, Truck} from "lucide-react";
import Link from "next/link";
import {adminWorkspaceClientService} from "@/services/admin/adminWorkspaceClientService";
import type {AdminCommissionSettings} from "@/types/adminWorkspace";
import {useAdminAccess} from "@/context/AdminAccessContext";

export function AdminPlatformSettingsWorkspace() {
 const [data,setData]=useState<AdminCommissionSettings|null>(null); const [value,setValue]=useState(""); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 const load=async()=>{try{const result=await adminWorkspaceClientService.getCommissionSettings();setData(result);setValue(String(result.defaultStoreCommissionBasisPoints/100));}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load settings.");}};
 useEffect(()=>{void load();},[]);
 const saveDefault=async()=>{const amount=Number(value);if(!Number.isFinite(amount)||amount<0||amount>50){setError("Enter a commission between 0% and 50%.");return;}setSaving(true);try{await adminWorkspaceClientService.saveDefaultStoreCommission(Math.round(amount*100));await load();}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save commission.");}finally{setSaving(false);}};
 if(!data)return <div className="flex min-h-64 items-center justify-center">{error?<p className="text-red-700">{error}</p>:<LoaderCircle className="h-8 w-8 animate-spin text-orange-600"/>}</div>;
 return <section><Link href="/admin/settings" className="mb-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-slate-700 ring-1 ring-slate-200"><ArrowLeft className="h-4 w-4"/>Back to settings</Link><p className="text-sm font-bold tracking-wide text-orange-600">PLATFORM SETTINGS</p><h1 className="mt-1 text-3xl font-bold">Store commission</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">The default applies to future settlements unless a store has a specific Admin override. Every change is audited; stores cannot edit these values.</p>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 <section className="mt-6 max-w-xl rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><h2 className="font-bold">Default store commission</h2><label className="mt-4 block text-sm font-semibold">LIA commission (%)<input type="number" min="0" max="50" step="0.01" value={value} onChange={(e)=>setValue(e.target.value)} className="mt-2 block w-full rounded-xl border border-slate-200 px-3 py-2.5"/></label><button disabled={saving} onClick={()=>void saveDefault()} className="mt-4 rounded-xl bg-orange-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving?"Saving…":"Save default"}</button></section>
 <section className="mt-6 overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-100"><div className="p-5"><h2 className="font-bold">Store overrides</h2><p className="mt-1 text-sm text-slate-500">Leave a store blank to use the {value || "default"}% platform commission.</p></div><div className="divide-y divide-slate-100">{data.stores.map(store=><StoreRow key={store.id} store={store} onSaved={load}/>)}</div></section></section>;
}
export function AdminSettingsMenu() {
 const {isMaster}=useAdminAccess();
 const entries=[{title:"Notification device",description:"Register this device and send a real push-notification test.",href:"/admin/settings/notifications",icon:Bell,ready:true},{title:"Store commission",description:"Default LIA commission and per-store overrides.",href:"/admin/settings/commissions",icon:Building2,ready:true},{title:"Driver payout policy",description:"Delivery commission, tips, and free-delivery incentive.",href:"/admin/settings/driver-payout",icon:Truck,ready:true},{title:"Default customer pricing",description:"Fallback fees and delivery limits when a store or customer has no zone.",href:"/admin/settings/customer-pricing",icon:CircleDollarSign,ready:true},{title:"Store applications",description:"Required documents and approval policy.",href:"/admin/settings/store-applications",icon:ClipboardCheck,ready:true},{title:"Driver applications",description:"Driver requirements, documents, and review policy.",href:"/admin/settings/driver-applications",icon:ShieldCheck,ready:true},{title:"Order & delivery",description:"Pickup delays, reminders, and delivery operations.",href:"/admin/settings/order-delivery",icon:PackageCheck,ready:true},{title:"Catalog search",description:"Rebuild safe public search profiles for stores and products.",href:"/admin/settings/catalog-search",icon:DatabaseZap,ready:true},...(isMaster?[{title:"Admin audit logs",description:"Protected history of administrator decisions and policy changes.",href:"/admin/settings/audit-logs",icon:History,ready:true}]:[])];return <section><p className="text-sm font-bold tracking-wide text-orange-600">PLATFORM SETTINGS</p><h1 className="mt-1 text-3xl font-bold">Settings</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Choose a policy area to review or update. Settings become editable only after the trusted backend flow reads them.</p><div className="mt-7 grid gap-4 md:grid-cols-2">{entries.map(entry=>{const Icon=entry.icon;const content=<><div className="rounded-xl bg-orange-50 p-3 text-orange-700"><Icon className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="font-bold text-slate-950">{entry.title}</h2>{!entry.ready&&<span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold text-slate-500">Next</span>}</div><p className="mt-1 text-sm leading-5 text-slate-500">{entry.description}</p></div></>;return entry.ready?<Link key={entry.title} href={entry.href!} className="flex gap-4 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100 transition hover:ring-orange-200">{content}</Link>:<article key={entry.title} className="flex gap-4 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100 opacity-75">{content}</article>})}</div></section>;
}
export function AdminDriverPayoutWorkspace(){const [data,setData]=useState<AdminCommissionSettings|null>(null);const [value,setValue]=useState("");const [error,setError]=useState("");const [saving,setSaving]=useState(false);const load=async()=>{try{const result=await adminWorkspaceClientService.getCommissionSettings();setData(result);setValue(String(result.defaultDriverCommissionBasisPoints/100));}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load driver payout policy.");}};useEffect(()=>{void load();},[]);const save=async()=>{const percent=Number(value);if(!Number.isFinite(percent)||percent<0||percent>50){setError("Enter a commission between 0% and 50%.");return;}setSaving(true);try{await adminWorkspaceClientService.saveDefaultDriverCommission(Math.round(percent*100));await load();}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save driver payout policy.");}finally{setSaving(false);}};if(!data)return <div className="flex min-h-64 items-center justify-center">{error?<p className="text-red-700">{error}</p>:<LoaderCircle className="h-8 w-8 animate-spin text-orange-600"/>}</div>;return <section><Link href="/admin/settings" className="mb-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-slate-700 ring-1 ring-slate-200"><ArrowLeft className="h-4 w-4"/>Back to settings</Link><p className="text-sm font-bold tracking-wide text-orange-600">DRIVER PAYOUT POLICY</p><h1 className="mt-1 text-3xl font-bold">Driver delivery commission</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">This is LIA’s retained percentage of the customer delivery fee. Drivers receive the remaining delivery fee and 100% of customer tips.</p>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<section className="mt-6 max-w-xl rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><label className="block text-sm font-semibold">LIA delivery commission (%)<input type="number" min="0" max="50" step="0.01" value={value} onChange={(e)=>setValue(e.target.value)} className="mt-2 block w-full rounded-xl border border-slate-200 px-3 py-2.5"/></label><button disabled={saving} onClick={()=>void save()} className="mt-4 rounded-xl bg-orange-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving?"Saving…":"Save policy"}</button></section><article className="mt-5 max-w-xl rounded-2xl bg-green-50 p-5 text-sm text-green-900"><b>Tip policy</b><p className="mt-1">Customer tips are currently protected as 100% driver earnings and are not editable from Admin Settings.</p></article></section>;}
function StoreRow({store,onSaved}:{store:AdminCommissionSettings["stores"][number];onSaved:()=>Promise<void>}){const [value,setValue]=useState(store.overrideBasisPoints===null?"":String(store.overrideBasisPoints/100));const [saving,setSaving]=useState(false);useEffect(()=>{setValue(store.overrideBasisPoints===null?"":String(store.overrideBasisPoints/100));},[store.overrideBasisPoints]);const save=async()=>{const percent=value.trim()===""?null:Number(value);if(percent!==null&&(!Number.isFinite(percent)||percent<0||percent>50))return;setSaving(true);try{await adminWorkspaceClientService.saveStoreCommissionOverride(store.id,percent===null?null:Math.round(percent*100));await onSaved();}finally{setSaving(false);}};return <div className="flex flex-wrap items-center gap-3 px-5 py-4"><p className="min-w-0 flex-1 font-bold">{store.name}</p><input aria-label={"Commission for "+store.name} type="number" min="0" max="50" step="0.01" value={value} onChange={(e)=>setValue(e.target.value)} placeholder="Default" className="w-28 rounded-lg border border-slate-200 px-3 py-2 text-sm"/><span className="text-sm text-slate-500">%</span><button disabled={saving} onClick={()=>void save()} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-bold text-white disabled:opacity-50">{saving?"Saving":"Save"}</button></div>}
