"use client";

import {useCallback, useEffect, useState} from "react";
import Link from "next/link";
import {Activity, AlertTriangle, CheckCircle2, LoaderCircle, RefreshCw, RotateCcw, Search} from "lucide-react";
import {useAdminAccess} from "@/context/AdminAccessContext";
import {adminWorkspaceClientService} from "@/services/admin/adminWorkspaceClientService";
import {AdminConfirmDialog} from "@/components/admin/AdminConfirmDialog";
import type {AdminOperationsOverview, AdminSearchResult} from "@/types/adminWorkspace";

export function AdminOperationsWorkspace() {
  const {canWrite} = useAdminAccess(); const writable = canWrite("operations");
  const [data, setData] = useState<AdminOperationsOverview | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState(""); const [results, setResults] = useState<AdminSearchResult[]>([]); const [searching, setSearching] = useState(false);
  const [retry, setRetry] = useState<AdminOperationsOverview["failedJobs"][number] | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { setLoading(true); setError(""); setData(await adminWorkspaceClientService.getOperationsOverview()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load system operations."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const search = async () => { if (query.trim().length < 2) return; try { setSearching(true); setError(""); setResults((await adminWorkspaceClientService.searchWorkspace(query.trim())).results); } catch (reason) { setError(reason instanceof Error ? reason.message : "Search failed."); } finally { setSearching(false); } };
  const confirmRetry = async () => { if (!retry) return; try { setBusy(true); await adminWorkspaceClientService.retryFailedJob(retry.type, retry.id, "Administrator requested recovery after reviewing the failure."); setRetry(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Recovery could not be scheduled."); } finally { setBusy(false); } };
  return <section><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-black tracking-wide text-orange-600">OPERATIONS CENTER</p><h1 className="mt-1 text-3xl font-black">System health & action queue</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">One protected view for failures, recoveries, operator work, and cross-workspace lookup. Recovery actions are whitelisted and audited.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/settings/operations" className="rounded-full border bg-white px-4 py-2 text-sm font-bold">Emergency & retention</Link><button data-admin-read-action type="button" onClick={() => void load()} className="inline-flex items-center gap-2 rounded-full border bg-white px-4 py-2 text-sm font-bold"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`}/>Refresh</button></div></div>
    {error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {loading && !data ? <div className="flex min-h-64 items-center justify-center"><LoaderCircle className="h-8 w-8 animate-spin text-orange-600"/></div> : data && <><div className="mt-6 grid gap-4 sm:grid-cols-3"><Metric title="Overall health" value={data.health.status === "healthy" ? "Healthy" : "Needs attention"} good={data.health.status === "healthy"}/><Metric title="Failed jobs" value={String(data.health.failedJobs)} good={data.health.failedJobs === 0}/><Metric title="Fatal app reports" value={String(data.health.fatalClientErrors)} good={data.health.fatalClientErrors === 0}/></div>
      <section className="mt-6 rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-black">Global search</h2><div className="mt-3 flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void search(); }} placeholder="Order number, record ID, or exact email" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-4 py-2.5"/><button data-admin-read-action type="button" onClick={() => void search()} disabled={searching || query.trim().length < 2} className="rounded-full bg-slate-950 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">{searching ? <LoaderCircle className="h-4 w-4 animate-spin"/> : <Search className="h-4 w-4"/>}</button></div>{results.length > 0 && <div className="mt-3 divide-y">{results.map((result) => <Link key={`${result.type}-${result.id}`} href={result.href} className="block py-3"><p className="font-bold">{result.title}</p><p className="text-xs text-slate-500">{result.type} · {result.subtitle || result.id}</p></Link>)}</div>}</section>
      <div className="mt-6 grid gap-5 xl:grid-cols-2"><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-black">Action required</h2><div className="mt-3 space-y-2">{data.actionQueue.length ? data.actionQueue.map((item) => <Link key={item.type} href={item.href} className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3 text-sm font-bold"><span>{item.label}</span><span className="rounded-full bg-orange-100 px-2.5 py-1 text-orange-800">{item.count}</span></Link>) : <Empty text="No queued operator actions."/>}</div></section><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-black">Failed-job recovery</h2><div className="mt-3 space-y-2">{data.failedJobs.length ? data.failedJobs.map((job) => <article key={`${job.type}-${job.id}`} className="rounded-xl bg-red-50 p-4"><div className="flex gap-3"><AlertTriangle className="h-5 w-5 shrink-0 text-red-600"/><div className="min-w-0 flex-1"><p className="font-bold">{job.title}</p><p className="mt-1 break-words text-xs text-red-800">{job.error || "No safe error summary was recorded."}</p><p className="mt-1 text-xs text-slate-500">{job.id}</p></div>{writable && job.type !== "deletion" ? <button type="button" onClick={() => setRetry(job)} className="h-fit rounded-full bg-white p-2 text-red-700" aria-label={`Retry ${job.title}`}><RotateCcw className="h-4 w-4"/></button> : null}</div></article>) : <Empty text="No failed jobs need manual recovery."/>}</div></section></div></>}
    <AdminConfirmDialog open={Boolean(retry)} title="Schedule this recovery?" description="The job will be reset only to its safe retry state. The existing scheduler and idempotency protections will perform the actual financial or delivery action. This decision is written to the admin audit log." confirmationLabel="Schedule retry" tone="warning" busy={busy} onCancel={() => setRetry(null)} onConfirm={() => void confirmRetry()}/>
  </section>;
}
function Metric({title, value, good}: {title: string; value: string; good: boolean}) { return <article className={`rounded-xl p-5 ${good ? "bg-emerald-50 text-emerald-900" : "bg-amber-50 text-amber-900"}`}><div className="flex items-center gap-2 text-sm font-bold">{good ? <CheckCircle2 className="h-5 w-5"/> : <Activity className="h-5 w-5"/>}{title}</div><p className="mt-3 text-2xl font-black">{value}</p></article>; }
function Empty({text}: {text: string}) { return <p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">{text}</p>; }
