"use client";
import {useEffect, useState} from "react";
import {Download, LoaderCircle, RefreshCw} from "lucide-react";
import {useAdminAccess} from "@/context/AdminAccessContext";
import {adminWorkspaceClientService} from "@/services/admin/adminWorkspaceClientService";
import type {AdminDailyFinanceReport} from "@/types/adminWorkspace";

const cash = (value: number) => new Intl.NumberFormat("en-US", {style: "currency", currency: "USD"}).format(value / 100);
const defaultReportDate = new Date(Date.now() - 86400000).toISOString().slice(0, 10);
export function AdminDailyFinanceReports() {
  const {canWrite} = useAdminAccess(); const [reports, setReports] = useState<AdminDailyFinanceReport[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [date, setDate] = useState(defaultReportDate);
  const load = async () => { try { setLoading(true); setError(""); setReports((await adminWorkspaceClientService.getDailyFinanceReports()).reports); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load daily finance reports."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const reconcile = async () => { try { setLoading(true); await adminWorkspaceClientService.runDailyFinancialReconciliation(date); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to reconcile this day."); setLoading(false); } };
  const exportCsv = () => { const header = ["date","orders","customer_payments","lia_revenue","stripe_fees","refunds","expected_transfers","completed_transfers","discrepancy","reconciled"]; const rows = reports.map((report) => [report.date, report.orderCount, report.totals.customerPayments, report.totals.platformRevenue, report.totals.stripeFees, report.totals.refunds, report.expectedTransfers, report.totals.transfersCompleted, report.discrepancyAmount, report.reconciled]); const csv = [header, ...rows].map((row) => row.join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], {type: "text/csv;charset=utf-8"})); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `lia-finance-${new Date().toISOString().slice(0,10)}.csv`; anchor.click(); URL.revokeObjectURL(url); };
  return <section className="mt-8 rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black">Daily reconciliation</h2><p className="mt-1 text-sm text-slate-500">Immutable ledger totals compared with completed participant transfers. Reports run automatically each morning and can be regenerated.</p></div><button data-admin-read-action type="button" disabled={!reports.length} onClick={exportCsv} className="inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm font-bold disabled:opacity-50"><Download className="h-4 w-4"/>Export CSV</button></div>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-4 flex flex-wrap gap-2"><input type="date" value={date} onChange={(event) => setDate(event.target.value)} className="rounded-xl border px-3 py-2 text-sm"/>{canWrite("finance") && <button type="button" disabled={loading} onClick={() => void reconcile()} className="inline-flex items-center gap-2 rounded-full bg-slate-950 px-4 py-2 text-sm font-bold text-white"><RefreshCw className="h-4 w-4"/>Reconcile day</button>}</div>{loading ? <div className="flex min-h-32 items-center justify-center"><LoaderCircle className="h-6 w-6 animate-spin text-orange-600"/></div> : reports.length === 0 ? <p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">No daily reconciliation has run yet. The scheduler creates yesterday&apos;s report at 4:30 AM Central.</p> : <div className="mt-5 overflow-x-auto"><table className="min-w-[850px] w-full text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="py-3">Date</th><th>Orders</th><th>Customer payments</th><th>LIA revenue</th><th>Expected transfers</th><th>Completed</th><th>Difference</th><th>Status</th></tr></thead><tbody>{reports.map((report) => <tr key={report.id} className="border-b border-slate-100"><td className="py-3 font-bold">{report.date}</td><td>{report.orderCount}</td><td>{cash(report.totals.customerPayments)}</td><td>{cash(report.totals.platformRevenue)}</td><td>{cash(report.expectedTransfers)}</td><td>{cash(report.totals.transfersCompleted)}</td><td className={report.discrepancyAmount ? "font-bold text-amber-700" : "text-emerald-700"}>{cash(report.discrepancyAmount)}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${report.reconciled ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>{report.reconciled ? "Reconciled" : "Review"}</span></td></tr>)}</tbody></table></div>}</section>;
}
