"use client";
/* eslint-disable react-hooks/set-state-in-effect -- the protected policy loader initializes this editor */
import Link from "next/link";
import {useEffect, useState} from "react";
import {ArrowLeft, LoaderCircle} from "lucide-react";
import {adminWorkspaceClientService} from "@/services/admin/adminWorkspaceClientService";
import type {AdminOrderDeliveryPolicy} from "@/types/adminWorkspace";

export function AdminOrderDeliverySettingsWorkspace() {
  const [policy, setPolicy] = useState<AdminOrderDeliveryPolicy | null>(null);
  const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [saved, setSaved] = useState(false);
  const load = async () => { try { setError(""); setPolicy((await adminWorkspaceClientService.getOrderDeliveryPolicy()).policy); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load order and delivery settings."); } };
  useEffect(() => { void load(); }, []);
  const update = (key: "minutesPerMile" | "defaultPreparationMinutes", value: number) => { if (policy) { setSaved(false); setPolicy({...policy, [key]: value}); } };
  const interval = (key: keyof AdminOrderDeliveryPolicy["reminderIntervalsMinutes"], value: number) => { if (policy) { setSaved(false); setPolicy({...policy, reminderIntervalsMinutes: {...policy.reminderIntervalsMinutes, [key]: value}}); } };
  const scheduling = <Key extends keyof AdminOrderDeliveryPolicy["scheduling"]>(key: Key, value: AdminOrderDeliveryPolicy["scheduling"][Key]) => { if (policy) { setSaved(false); setPolicy({...policy, scheduling: {...policy.scheduling, [key]: value}}); } };
  const save = async () => { if (!policy) return; setSaving(true); setError(""); try { await adminWorkspaceClientService.saveOrderDeliveryPolicy(policy); setSaved(true); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save order and delivery settings."); } finally { setSaving(false); } };
  if (!policy) return <div className="flex min-h-64 items-center justify-center">{error ? <p className="text-red-700">{error}</p> : <LoaderCircle className="h-8 w-8 animate-spin text-orange-600"/>}</div>;
  return <section><Link href="/admin/settings" className="mb-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-slate-700 ring-1 ring-slate-200"><ArrowLeft className="h-4 w-4"/>Back to settings</Link><p className="text-sm font-bold tracking-wide text-orange-600">ORDER & DELIVERY</p><h1 className="mt-1 text-3xl font-bold">Order and delivery policy</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Control delivery estimates, scheduled fulfillment, capacity defaults, and store-action reminders.</p>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{saved && <p className="mt-4 rounded-xl bg-green-50 p-3 text-sm text-green-800">Order and delivery policy saved and audited.</p>}
    <section className="mt-6 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><h2 className="font-bold">Delivery estimates</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Minutes per route mile" value={policy.minutesPerMile} min={1} max={60} onChange={(value) => update("minutesPerMile", value)}/><Field label="Default preparation minutes" value={policy.defaultPreparationMinutes} min={0} max={180} onChange={(value) => update("defaultPreparationMinutes", value)}/></div></section>
    <section className="mt-5 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><h2 className="font-bold">Scheduled fulfillment</h2><p className="mt-1 text-sm text-slate-500">Stores must also opt in. Checkout validates each window against current hours, timezone, lead time, and capacity.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Toggle label="Allow scheduled pickup" value={policy.scheduling.pickupEnabled} onChange={(value) => scheduling("pickupEnabled", value)}/><Toggle label="Allow scheduled delivery" value={policy.scheduling.deliveryEnabled} onChange={(value) => scheduling("deliveryEnabled", value)}/><Field label="Maximum days ahead" value={policy.scheduling.maximumDaysAhead} min={1} max={30} onChange={(value) => scheduling("maximumDaysAhead", value)}/><Field label="Slot interval (minutes)" value={policy.scheduling.slotIntervalMinutes} min={15} max={120} onChange={(value) => scheduling("slotIntervalMinutes", value)}/><Field label="Default orders per slot" value={policy.scheduling.defaultOrdersPerSlot} min={1} max={100} onChange={(value) => scheduling("defaultOrdersPerSlot", value)}/></div></section>
    <section className="mt-5 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><h2 className="font-bold">Store action reminders</h2><p className="mt-1 text-sm text-slate-500">The scheduler sends reminders only for paid orders still awaiting action.</p><div className="mt-4 grid gap-4 sm:grid-cols-3"><Field label="Pending (minutes)" value={policy.reminderIntervalsMinutes.pending} min={5} max={1440} onChange={(value) => interval("pending", value)}/><Field label="Accepted (minutes)" value={policy.reminderIntervalsMinutes.accepted} min={5} max={1440} onChange={(value) => interval("accepted", value)}/><Field label="Preparing (minutes)" value={policy.reminderIntervalsMinutes.preparing} min={5} max={1440} onChange={(value) => interval("preparing", value)}/></div></section>
    <div className="sticky bottom-4 mt-6 flex justify-end rounded-2xl bg-white/95 p-3 shadow-lg ring-1 ring-slate-200 backdrop-blur"><button disabled={saving} onClick={() => void save()} className="rounded-xl bg-orange-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{saving ? "Saving…" : "Save order and delivery policy"}</button></div></section>;
}
function Field({label, value, min, max, onChange}: {label: string; value: number; min: number; max: number; onChange: (value: number) => void}) { return <label className="text-sm font-semibold text-slate-800">{label}<input type="number" min={min} max={max} step="1" value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-2 block w-full rounded-xl border border-slate-200 px-3 py-2.5"/></label>; }
function Toggle({label, value, onChange}: {label: string; value: boolean; onChange: (value: boolean) => void}) { return <label className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 p-4 text-sm font-bold text-slate-800">{label}<input type="checkbox" checked={value} onChange={(event) => onChange(event.target.checked)} className="h-5 w-5 accent-orange-600"/></label>; }
