"use client";

import { useEffect, useState } from "react";
import { Banknote, CheckCircle2, Clock3, FileCheck2, ShieldAlert, WalletCards } from "lucide-react";
import { BrandedLoader } from "@/components/ui/BrandedLoader";
import { driverWorkspaceClientService } from "@/services/driver/driverWorkspaceClientService";
import type { DriverWorkspaceSummary } from "@/types/driverWorkspace";

const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);
function statusInfo(status: DriverWorkspaceSummary["status"]) { if (status === "approved") return ["Approved", "bg-green-100 text-green-700", CheckCircle2] as const; if (status === "suspended") return ["Suspended", "bg-red-100 text-red-700", ShieldAlert] as const; return ["Pending approval", "bg-amber-100 text-amber-800", Clock3] as const; }

export default function DriverDashboardPage() {
  const [summary, setSummary] = useState<DriverWorkspaceSummary | null>(null);
  useEffect(() => { void driverWorkspaceClientService.getSummary().then(setSummary).catch(() => setSummary(null)); }, []);
  if (!summary) return <BrandedLoader message="Loading Driver Dashboard" />;
  const [label, color, Icon] = statusInfo(summary.status);
  const docsApproved = summary.documents.filter((document) => document.reviewStatus === "approved").length;
  return <section className="mx-auto max-w-4xl"><p className="text-sm font-semibold text-orange-600">DRIVER DASHBOARD</p><h1 className="mt-1 text-3xl font-bold">Welcome {summary.firstName}</h1><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><article className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><p className="text-sm text-slate-500">Status</p><div className={`mt-3 inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-sm font-bold ${color}`}><Icon className="h-4 w-4" />{label}</div></article><article className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><p className="text-sm text-slate-500">Stripe status</p><p className="mt-3 text-lg font-bold capitalize">{summary.stripe.status.replaceAll("_", " ")}</p></article><article className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><p className="text-sm text-slate-500">Documents</p><p className="mt-3 text-lg font-bold">{docsApproved}/{summary.documents.length} approved</p></article><article className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><p className="text-sm text-slate-500">Total earnings</p><p className="mt-3 text-lg font-bold">{money(summary.totals.lifetime)}</p></article></div><div className="mt-6 grid gap-4 md:grid-cols-2"><article className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><div className="flex items-center gap-2 font-bold"><Banknote className="h-5 w-5 text-green-600" />Last payment</div><p className="mt-4 text-2xl font-bold">{summary.lastPayment ? money(summary.lastPayment.amount) : "No payments yet"}</p>{summary.lastPayment && <p className="mt-1 text-sm text-slate-500">Delivery #{summary.lastPayment.deliveryId}</p>}</article><article className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><div className="flex items-center gap-2 font-bold"><WalletCards className="h-5 w-5 text-orange-600" />Payout readiness</div><p className="mt-4 text-sm text-slate-600">{summary.stripe.payoutsEnabled ? "Your payout account is ready." : "Complete or update Stripe Connect to receive payouts."}</p></article></div><article className="mt-6 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><div className="flex items-center gap-2 font-bold"><FileCheck2 className="h-5 w-5 text-orange-600" />Document review</div><div className="mt-4 grid gap-3 sm:grid-cols-3">{summary.documents.map((document) => <div key={document.label} className="rounded-xl bg-slate-50 p-3"><p className="text-sm font-medium">{document.label}</p><p className="mt-1 text-sm capitalize text-slate-500">{document.reviewStatus}</p><p className="mt-1 text-xs text-slate-400">{document.expirationDate ? `Expires ${new Date(`${document.expirationDate}T00:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}` : "No expiration date"}</p></div>)}</div></article></section>;
}
