/*
|--------------------------------------------------------------------------
| Product Domain Model
|--------------------------------------------------------------------------
|
| Shared product model used throughout LIA.
|
| This model is used by:
|
| • Customer store pages
| • Search
| • Cart
| • Store inventory
| • Admin panel
| • Order creation
|
| Pages should not create separate Product interfaces.
|
*/

import type { Promotion } from "./promotion";



/**
 * Product size or package quantity.
 *
 * Examples:
 *
 * • 5 lb
 * • 500 ml
 * • 12 oz
 */
export interface ProductSize {
  value: number;

  unit: string;
}



/*
|--------------------------------------------------------------------------
| Product Image Status
|--------------------------------------------------------------------------
|
| Tracks the asynchronous image-processing pipeline.
|
*/

export type ProductImageStatus =
  | "none"
  | "uploading"
  | "processing"
  | "enhancing"
  | "ready"
  | "failed";

  /*
|--------------------------------------------------------------------------
| Product Image Variants
|--------------------------------------------------------------------------
|
| Responsive customer-facing images generated by Firebase Functions.
|
*/

export type ProductImageVariantName =
  | "thumbnail"
  | "small"
  | "medium"
  | "large";

export interface ProductImageVariant {
  /**
   * Variant name.
   */
  name: ProductImageVariantName;

  /**
   * Firebase Storage path.
   */
  path: string;

  /**
   * Customer-facing download URL.
   */
  url: string;

  /**
   * Final image dimensions.
   */
  width: number;

  height: number;

  /**
   * Final compressed file size.
   */
  sizeBytes: number;

  /**
   * Current optimized format.
   */
  format: "webp";
}

export type ProductImageVariants =
  Partial<
    Record<
      ProductImageVariantName,
      ProductImageVariant
    >
  >;

  /*
|--------------------------------------------------------------------------
| Product Gallery Image
|--------------------------------------------------------------------------
|
| Represents one independently processed image belonging to a product.
|
| Examples:
|
| • Front package image
| • Back label
| • Nutrition label
| • Ingredients
| • Side view
| • Alternate angle
|
*/

export interface ProductGalleryImage {
  /**
   * Unique ID assigned before uploading the image.
   */
  id: string;

  /**
   * Human-readable description used for accessibility.
   *
   * Example:
   * "Back nutrition label of Maggi seasoning"
   */
  altText: string;

  /**
   * Ordering position in the customer gallery.
   *
   * The primary image normally has position 0.
   */
  position: number;

  /**
   * Whether this image is the product's main customer-facing image.
   */
  isPrimary: boolean;

  /**
   * Current state of this image's independent processing pipeline.
   */
  status: ProductImageStatus;

  /**
   * Backward-compatible URL for this gallery image.
   *
   * This should point to the configured default variant when processing
   * finishes.
   */
  imageUrl: string;

  /**
   * Responsive image variants generated by Firebase Functions.
   */
  imageVariants?: ProductImageVariants;

  /**
   * Temporary original Storage path while processing is underway.
   */
  originalImagePath?: string | null;

  /**
   * Default optimized image path retained for compatibility and cleanup.
   */
  optimizedImagePath?: string | null;

  /**
   * Processing error associated with this specific image.
   */
  imageError?: string | null;

  /**
   * ISO timestamp indicating when this gallery image was created.
   */
  createdAt?: string;

  /**
   * ISO timestamp indicating the most recent update.
   */
  updatedAt?: string;
}

/**
 * Product domain model.
 */
export interface Product {
  /**
   * Firestore document ID.
   */
  id: string;

  /**
   * Store that owns this product.
   */
  storeId: string;

  /**
   * Product information.
   */
  name: string;

  description: string;

  category: string;

  brand?: string;

  /**
   * Selling price.
   */
  price: number;

  /**
   * Current inventory quantity.
   */
  stock: number;

  /*
  |--------------------------------------------------------------------------
  | Product Image Processing
  |--------------------------------------------------------------------------
  */

  /**
   * Optimized WebP URL displayed throughout the application.
   */
  imageUrl: string;

    /**
   * Responsive WebP variants generated from the same processed product image.
   *
   * Legacy products may not have this field, so components should fall back
   * to imageUrl when a requested variant is unavailable.
   */
  imageVariants?: ProductImageVariants;

  /**
   * Current state of the asynchronous image-processing pipeline.
   *
   * Legacy products may not have this field, so it remains optional.
   */

    /**
   * Complete product image gallery.
   *
   * This remains optional during migration because existing products use only
   * imageUrl and imageVariants.
   */
  images?: ProductGalleryImage[];

  /**
   * ID of the gallery image currently used as the primary image.
   *
   * Legacy products may not have this value.
   */
  primaryImageId?: string | null;
  imageStatus?: ProductImageStatus;

  /**
   * Storage path of the original uploaded image.
   *
   * The background function reads this file and may delete it after
   * successfully creating the optimized WebP.
   */
  originalImagePath?: string;

  /**
   * Storage path of the optimized WebP image.
   */
  optimizedImagePath?: string;

  /**
   * Human-readable processing error for debugging and UI feedback.
   */
  imageError?: string | null;

  /**
   * Store-managed inventory identifier.
   */
  sku: string;

  /**
   * Whether customers can currently purchase the product.
   */
  isAvailable: boolean;

  /**
   * Whether the product should be highlighted.
   */
  featured: boolean;

  /**
   * Optional package size.
   */
  size?: ProductSize | null;

  /**
   * Internal customer rating.
   */
  rating?: number;

  /**
   * Number of submitted reviews.
   */
  reviewCount?: number;

  /**
   * Number of units sold.
   */
  soldCount?: number;

  /**
   * Optional active promotion.
   */
  promotion?: Promotion | null;

  /**
   * Audit timestamps stored as ISO strings.
   */
  createdAt: string;

  updatedAt: string;
}
