/*
|--------------------------------------------------------------------------
| Firebase Messaging Service Worker
|--------------------------------------------------------------------------
|
| A public/ file cannot read environment variables, so it would serve the
| placeholder Firebase configuration unchanged. This route generates the
| worker using the browser-safe Firebase configuration at request time.
|
*/

export const dynamic = "force-dynamic";
export const revalidate = 0;

export async function GET() {
  const firebaseConfig = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  };

  const worker = `/* Firebase Cloud Messaging worker generated by LIA. */
importScripts("https://www.gstatic.com/firebasejs/12.15.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/12.15.0/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(firebaseConfig)});

const messaging = firebase.messaging();

self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});

messaging.onBackgroundMessage((payload) => {
  const notificationTitle = payload.notification?.title ?? "LIA";
  const candidate = payload.data?.deepLink;
  const deepLink = typeof candidate === "string" &&
    candidate.startsWith("/") &&
    !candidate.startsWith("//")
    ? candidate
    : "/home";

  self.registration.showNotification(notificationTitle, {
    body: payload.notification?.body,
    icon: "/icon/icon-192.png",
    badge: "/icon/icon-192.png",
    data: {deepLink},
  });
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();

  const candidate = event.notification.data?.deepLink;
  const deepLink = typeof candidate === "string" &&
    candidate.startsWith("/") &&
    !candidate.startsWith("//")
    ? candidate
    : "/home";
  const destination = new URL(deepLink, self.location.origin).href;

  event.waitUntil((async () => {
    const windows = await self.clients.matchAll({
      type: "window",
      includeUncontrolled: true,
    });
    const existing = windows.find((client) =>
      client.url.startsWith(self.location.origin),
    );

    if (existing) {
      await existing.focus();
      await existing.navigate(destination);
      return;
    }

    await self.clients.openWindow(destination);
  })());
});`;

  return new Response(worker, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      "Cache-Control": "no-cache, no-store, must-revalidate",
      "Service-Worker-Allowed": "/",
    },
  });
}
