/*
|--------------------------------------------------------------------------
| Firebase Messaging Service Worker
|--------------------------------------------------------------------------
|
| A public/ file cannot read environment variables, so it would serve the
| placeholder Firebase configuration unchanged. This route generates the
| worker using the browser-safe Firebase configuration at request time.
|
*/

export const dynamic = "force-dynamic";
export const revalidate = 0;

export async function GET() {
  const firebaseConfig = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  };

  const worker = `/* Firebase Cloud Messaging worker generated by LIA. */
importScripts("https://www.gstatic.com/firebasejs/12.15.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/12.15.0/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(firebaseConfig)});

const messaging = firebase.messaging();

self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});

messaging.onBackgroundMessage((payload) => {
  const notificationTitle = payload.notification?.title ?? "LIA";

  self.registration.showNotification(notificationTitle, {
    body: payload.notification?.body,
    icon: "/icon/icon-192.png",
    badge: "/icon/icon-192.png",
  });
});`;

  return new Response(worker, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      "Cache-Control": "no-cache, no-store, must-revalidate",
      "Service-Worker-Allowed": "/",
    },
  });
}
