import type {LegalSection} from "./customerTerms";

export const customerPrivacyIntroduction = [
  "LIA respects your privacy. This Privacy Policy explains how LIA collects, uses, discloses, retains, and protects personal information when you use the LIA website, customer applications, marketplace, delivery services, and related services.",
  "This Policy primarily applies to customers and prospective customers. Separate notices or agreements may apply to participating merchants, drivers, employees, contractors, and other business partners. By using LIA, you acknowledge the practices described here.",
];

export const customerPrivacySections: LegalSection[] = [
  {title: "1. Information we collect", paragraphs: ["The information collected depends on how you interact with LIA. It may come directly from you, automatically from your device, from participating Stores and delivery providers, or from service providers operating the Platform."]},
  {title: "2. Account, profile, and authentication information", paragraphs: ["LIA may collect your name, email, telephone number, account identifier, optional profile image, saved delivery addresses, preferences, communication choices, authentication identifiers, verification status, security information, and information you submit through your profile.", "Firebase Authentication and related providers handle passwords, authentication credentials, and sign-in tokens. LIA uses this information to create, authenticate, protect, and maintain accounts.", "If you use Google or Apple sign-in, the authentication provider may provide LIA with an account identifier, email address, name, profile information, authentication tokens, and verification information according to your provider settings and the provider’s policies. LIA does not receive your Google or Apple account password."]},
  {title: "3. Orders and transactions", paragraphs: ["LIA may maintain product information, Store identity, quantities, sizes, fulfillment method, pickup or delivery location, pickup instructions, pickup-code and handoff confirmation records, subtotal, taxes, service and delivery fees, driver tips, discounts, total, payment status, order status, timestamps, refunds, cancellations, fulfillment status, and order history.", "Plain pickup codes and their searchable security values are removed from active pickup-code storage after successful handoff, although related order status, timestamps, and confirmation records may remain.", "If substitution or variable-weight functionality is introduced, the related preferences and price adjustments may also be processed. This information supports fulfillment, customer service, disputes, fraud prevention, financial records, and Platform improvement."]},
  {title: "4. Payments and taxes", paragraphs: ["Stripe processes customer payments and may collect card, billing, payment-method, authorization, fraud-prevention, and transaction information. LIA receives limited information such as payment status, method type, transaction identifiers, Stripe customer identifiers, and limited display information.", "Stripe Tax may process product tax classifications, line-item amounts, Store origin information, the customer’s delivery or pickup location, applicable jurisdiction, calculated tax, taxability results, and refund-related tax reversals. LIA retains tax calculations and item-level tax snapshots for order processing, refunds, reconciliation, reporting, and legal compliance.", "LIA does not store complete payment-card numbers or security codes. If saved payment methods are offered, Stripe will handle the underlying credentials according to its security, privacy, and legal obligations."]},
  {title: "5. Fulfillment and location information", paragraphs: ["LIA may process delivery and pickup addresses, recipient name, contact number, instructions, Store location, route distance, delivery zone, pickup-distance eligibility, fulfillment status, driver assignment, estimates, timestamps, provider identifiers, approximate network location, and precise geographic coordinates derived from addresses you provide.", "This information supports nearby Store discovery, delivery and pickup eligibility, driving-distance and fee calculations, tax determination, fulfillment, tracking, accuracy, fraud prevention, and support. LIA does not currently access the customer device’s GPS location. Customers provide or select an address for location-dependent features."]},
  {title: "6. Support, complaints, refunds, and uploads", paragraphs: ["When you request support or report an order problem, LIA may collect messages, descriptions, product and packaging information, photographs, delivery and Store information, refund reason and amount, and other evidence reasonably needed for investigation.", "Uploaded profile images, complaint photographs, and other content may be stored and processed using cloud storage, optimization, security, and delivery technologies. Do not provide content you lack the right to share."]},
  {title: "7. Information from Stores and delivery providers", paragraphs: ["Stores may provide acceptance, inventory, preparation, missing-item, cancellation, fulfillment, readiness, pickup instructions, handoff, pickup-code verification, exception, and completion information.", "For delivery orders, Drivers and Shipday may provide assignment, carrier identifiers, Store pickup and customer delivery progress, timestamps, exceptions, tracking information, and completion records. Shipday is not used to dispatch customer pickup orders.", "LIA uses this information to operate the marketplace and provide real-time or near-real-time pickup and delivery updates."]},
  {title: "8. Device, technical, security, and diagnostic information", paragraphs: ["LIA and its providers may collect device type, operating system, app version, browser, device or installation identifiers, IP address, language, app activity, route names, network state, error details, security events, and diagnostic or performance information.", "Security systems such as Firebase App Check and reCAPTCHA Enterprise may process app, browser, installation, network, device-integrity, request, and risk signals to distinguish legitimate application traffic from automated, fraudulent, or abusive activity.", "Native crash reports may include application version, device and operating-system information, route or application area, sanitized stack information, diagnostic context, and an authenticated account identifier when available. LIA’s browser error reporter intentionally avoids storing URL query strings that may contain customer input.", "This information supports Platform operation, authentication, troubleshooting, fraud prevention, security, crash and performance monitoring, and improvement."]},
  {title: "9. Push notifications", paragraphs: ["If enabled, LIA processes device notification tokens, platform information, preferences, registration and delivery status, and information needed to route notifications. Notifications may concern orders, Stores, pickup or delivery, payments, refunds, security, products, or permitted promotions.", "Permission can be controlled through device settings and supported notification categories through LIA settings. Depending on device settings, notification titles or summaries may appear on a locked screen or be visible to another person with access to the device. You can manage notification visibility through operating-system settings."]},
  {title: "10. How LIA uses information", paragraphs: ["LIA uses personal information to create and authenticate accounts; process payments, taxes, orders, refunds, and cancellations; coordinate Stores, pickup, and delivery; calculate zones, routes, and fees; provide tracking and support; send transactional communications; investigate complaints; prevent fraud; protect safety and security; maintain legal and financial records; enforce agreements; diagnose problems; measure performance; improve and develop features; and protect legal rights."]},
  {title: "11. Communications and marketing", paragraphs: ["LIA may send verification, security, order, payment, delivery, refund, cancellation, legal, and support communications needed to operate the service.", "Where legally permitted and appropriately authorized, LIA may send marketing concerning Stores, products, promotions, discounts, and features. Eligible marketing can be unsubscribed from without stopping essential transactional or security communications."]},
  {title: "12. Stores and delivery providers", paragraphs: ["LIA shares only information reasonably needed for fulfillment, support, and safety. A Store may receive recipient name, operationally necessary contact information, order selections, pickup or delivery instructions, and relevant fulfillment or problem information. For delivery orders, delivery personnel and Shipday may receive recipient, address, contact, instruction, Store pickup, and order-identifier information.", "Participating Stores are independent businesses and may have separate legal obligations concerning order, transaction, food-safety, tax, and customer-service records. They must use information received from LIA only for authorized marketplace purposes and applicable legal obligations.", "Stores and delivery providers are not authorized by LIA to sell, use for unrelated marketing, harass, or solicit customers using information obtained through LIA."]},
  {title: "13. Technology and service providers", paragraphs: ["LIA uses Firebase and Google Cloud for authentication, database, storage, Cloud Functions, and messaging; Firebase App Check and Google reCAPTCHA Enterprise for application attestation, abuse prevention, and security risk assessment; Firebase Crashlytics, Firebase Performance, and LIA’s Firebase-backed error reporting for reliability, crash reporting, diagnostics, and performance measurement; Stripe and Stripe Tax for payment processing, tax calculation and reporting, refunds, payment-method handling, and fraud controls; Shipday for delivery coordination; Google Maps and Routes for address, geocoding, route, and distance services; Resend for transactional email; Vercel for website hosting and delivery; and Cloudflare for domain, DNS, and applicable network or security services.", "These providers process information in connection with the services they provide to LIA and may also process information to satisfy their independent security, fraud-prevention, tax, payment, or legal obligations, as described in their applicable terms and privacy notices."]},
  {title: "14. Legal, safety, and business disclosures", paragraphs: ["LIA may disclose information to comply with law or lawful process, respond to government requests, protect customers, Stores, drivers, or others, investigate fraud, enforce agreements, protect rights or property, or respond to emergencies.", "Information may be transferred in a merger, acquisition, financing, reorganization, asset sale, or similar transaction where permitted by law. A successor remains subject to applicable privacy obligations."]},
  {title: "15. No sale of personal information", paragraphs: ["LIA does not currently sell customer personal information, including for monetary payment or other valuable consideration as those terms are defined under applicable state privacy laws. LIA does not currently share personal information for cross-context behavioral advertising or process it for targeted advertising.", "If future practices constitute a regulated sale, sharing, targeted advertising, or other processing requiring a choice, LIA will update its disclosures and provide required choices before beginning that practice."]},
  {title: "16. Data retention", paragraphs: ["LIA retains information only as long as reasonably necessary to provide the service and meet legitimate legal, accounting, tax, payment, fraud, safety, security, dispute, and regulatory obligations. Retention depends on account activity, transaction history, refunds, chargebacks, investigations, legal claims, and applicable limitation periods.", "Operational records such as expired push registrations and client error reports are subject to scheduled cleanup. Transaction, payment, refund, legal-acceptance, deletion-audit, and compliance records may be retained longer when necessary. LIA deletes, minimizes, anonymizes, or de-identifies information when it is no longer reasonably needed."]},
  {title: "17. Account deletion", paragraphs: ["Customers can initiate deletion through Profile in the LIA application. A public explanation and external request route are available at https://www.liamarketplace.com/legal/account-deletion.", "After verification and the disclosed review or grace process, LIA deletes or de-identifies eligible account information. Limited tax, accounting, transaction, refund, chargeback, fraud, security, legal, regulatory, and audit records may remain where permitted or required. Where practical, retained information is minimized or de-identified."]},
  {title: "18. Security", paragraphs: ["LIA uses administrative, technical, and organizational safeguards such as authentication, access restrictions, cloud security controls, encryption where appropriate, specialized payment processing, monitoring, Firestore and Storage rules, restricted administrator permissions, and audit logs.", "No internet-connected service can guarantee absolute security. Protect your device and credentials, and never send full card numbers, security codes, or passwords through ordinary support messages or email."]},
  {title: "19. Children’s privacy", paragraphs: ["LIA customer accounts are intended for people age 18 or older. LIA does not knowingly collect personal information from a child through a customer account. A parent or guardian who believes a child created an account should contact info@liamarketplace.com."]},
  {title: "20. Privacy choices", paragraphs: ["Depending on available functionality and applicable law, you may review or correct profile information, change saved addresses, manage notifications and marketing preferences, manage supported payment methods, request deletion, and contact LIA about personal information.", "LIA may reasonably verify identity before providing access to or changing sensitive information. Removing or changing an address does not remove address and location information retained with completed transactions or other records that LIA must reasonably maintain. Disabling push does not prevent necessary email or in-app transactional communications."]},
  {title: "21. Cookies and local technologies", paragraphs: ["The website and PWA may use cookies, local storage, IndexedDB, service workers, or similar technologies for sessions, preferences, security, performance, safe static assets, and core functionality. LIA does not currently use cross-site behavioral advertising technologies. Required consent and disclosures will be added before introducing non-essential tracking that requires them."]},
  {title: "22. Analytics and automated systems", paragraphs: ["Firebase Crashlytics, Firebase Performance, and LIA diagnostic reporting may help identify crashes and errors, measure route and load performance, and improve features. LIA does not call information anonymous unless it satisfies the applicable standard.", "Automated systems may assist with fraud detection, security, tax calculations, delivery-zone and route calculations, search, recommendations, notifications, and operational prioritization. LIA does not currently use automated decisions that independently produce legal or similarly significant effects on customers."]},
  {title: "23. Third-party links", paragraphs: ["LIA may link to independently operated websites or services. LIA does not control their separate privacy practices, and you should review their policies."]},
  {title: "24. Policy changes and versions", paragraphs: ["LIA may update this Policy when services, providers, data practices, laws, or operations change. Each version identifies its effective date and last-updated date. Material changes may be announced through the Platform, email, or another appropriate method.", "When legally required, LIA will obtain consent before materially different processing. LIA records the legal-document identifier, version, document hash, authenticated account, acceptance or acknowledgment result, and server timestamp as evidence of the version presented to the customer. An administrator may designate a material new version as requiring acknowledgment before account-based services continue."]},
  {title: "25. United States and state privacy rights", paragraphs: ["LIA is currently focused on the United States. Information may be processed in the United States and locations where authorized providers operate, subject to applicable safeguards.", "Residents of certain states may have applicable access, correction, deletion, portability, disclosure, opt-out, and appeal rights depending on statutory thresholds and LIA’s activities. Submit a request to info@liamarketplace.com. LIA will verify and respond to applicable requests as required by law."]},
  {title: "26. Contact LIA", paragraphs: ["Privacy and support requests: info@liamarketplace.com", "Website: https://www.liamarketplace.com", "Account deletion information: https://www.liamarketplace.com/legal/account-deletion"]},
];
