import type {LegalSection} from "./customerTerms";

export const customerRefundIntroduction = [
  "This Refund and Cancellation Policy explains the current LIA Marketplace process for cancelled orders, order problems, claim evidence, and approved refunds.",
  "This Policy is part of the LIA Customer Terms of Service. It does not limit rights that cannot be waived under applicable law.",
];

export const customerRefundSections: LegalSection[] = [
  {title: "1. Order cancellation before store acceptance", paragraphs: ["A customer cannot directly cancel an order after submitting it. Contact LIA Support as soon as possible if help is needed; a cancellation request is not guaranteed.", "A participating store may cancel an order only while it is still pending and before the store accepts it. When a store cancels a confirmed paid order at that stage, LIA automatically creates a full refund of the customer payment to the original payment method."]},
  {title: "2. After a store accepts an order", paragraphs: ["After accepting an order, the store cannot cancel it through the store workspace. The store must contact LIA Support if fulfillment cannot continue. LIA will review the order, delivery, payment, and surrounding circumstances and determine the appropriate action.", "Customers who need assistance after submitting an order must use Order Help or contact LIA Support. Contacting support does not itself cancel an order or guarantee a refund."]},
  {title: "3. Problems that may qualify for review", paragraphs: ["LIA may review claims involving a missing item, incorrect item, damaged item, material quality or safety issue, delivery failure, duplicate charge, or another material order problem.", "Submitting a claim starts an administrative review; it is not an automatic refund. LIA may approve a full refund, partial refund, or no refund based on the paid order record, fulfillment information, evidence, applicable law, and the circumstances within each party’s control."]},
  {title: "4. When a claim may be submitted", paragraphs: ["Item, damage, quality, and similar fulfillment claims may be submitted after delivery is completed. A delivery-failure claim may also be submitted after an order is cancelled.", "For a delivery that is still active, delayed, or progressing, use Order Help first so LIA can investigate and assist before treating it as a delivery failure."]},
  {title: "5. One claim per order", paragraphs: ["LIA accepts one customer refund claim for each order. Include every affected item and all relevant details for that order in the claim description.", "A cancelled order and a customer claim are handled at the order level. Creating repeated or overlapping claims for the same order is not supported."]},
  {title: "6. Evidence requirements", paragraphs: ["A clear photograph is required for damaged-item and material quality claims because the condition of the product is relevant to review. A photo is not required merely to report that an item is missing.", "LIA may request other reasonably available information, such as packaging, labels, item names, quantities, delivery details, messages, or payment records. Do not alter evidence or submit information that is false or misleading. Evidence may be unavailable for some delivery failures or missing items, and LIA will review the records that reasonably exist."]},
  {title: "7. Refund amount", paragraphs: ["An approved full refund may include the amounts actually paid for merchandise, tax, delivery fee, service fee, and driver tip. An approved partial refund is limited to the affected paid components and cannot exceed the remaining unrefunded customer payment.", "Promotions and discounts reduce the amount paid and therefore may reduce the refundable amount. LIA does not promise store credit, replacement products, exchanges, or physical returns through the current claim workflow."]},
  {title: "8. Refund method and timing", paragraphs: ["Approved refunds are sent to the original payment method through LIA’s payment processor. LIA records the refund request and processing result, but the customer’s bank or payment network controls when returned funds appear.", "If automated processing fails or only part of a refund completes, LIA may retry or investigate the transaction. Customers can view available refund updates in the order and notification experience or contact LIA Support."]},
  {title: "9. Claims involving customer information or access", paragraphs: ["Refund eligibility may be affected when a failure is primarily caused by materially incorrect delivery information, an inaccessible location, inability to reach the customer, unsafe access, or failure to follow reasonable delivery instructions.", "LIA will consider the order record and the circumstances rather than automatically denying every claim involving a delivery difficulty."]},
  {title: "10. Abuse, payment disputes, and legal rights", paragraphs: ["False claims, manipulated evidence, repeated misuse, or fraudulent payment disputes may result in claim denial, account restrictions, or other lawful action. Customers retain rights provided by applicable law and their financial institution.", "When practical, contact LIA first so the transaction can be investigated and the existing refund process can be used."]},
  {title: "11. Contact LIA", paragraphs: ["Order support is available through the signed-in Order Help experience.", "Email: info@liamarketplace.com", "Website: https://www.liamarketplace.com"]},
];
