export interface LegalSection {
  title: string;
  paragraphs: string[];
  items?: string[];
}

export const customerTermsIntroduction = [
  "These Customer Terms of Service (Terms) govern your access to and use of the LIA website, mobile applications, and related services (collectively, the LIA Platform or Platform).",
  "By selecting “I agree,” creating your account, or continuing after being presented with these Terms, you acknowledge that you have read and agree to these Terms. If you do not agree, do not create an account or use the Platform.",
];

export const customerTermsSections: LegalSection[] = [
  {title: "1. About LIA", paragraphs: ["LIA operates a technology-enabled marketplace through which customers can discover participating stores, browse products, place orders, make payments, choose an available pickup or delivery method, receive updates, and access related services.", "Products are generally sold by independently owned participating merchants. Unless specifically stated otherwise, LIA is not the manufacturer, producer, or owner of those products. LIA provides marketplace technology, payment facilitation, pickup and delivery coordination, customer support, and related services."]},
  {title: "2. Eligibility", paragraphs: ["You must be at least 18 years old and legally capable of entering into a binding agreement to create a LIA account. LIA does not currently support the purchase of age-restricted products. If such products are offered later, additional eligibility and identity-verification requirements may apply."]},
  {title: "3. Customer account and verification", paragraphs: ["You agree to provide accurate and current name, email, telephone, delivery or pickup contact, and other information reasonably required to provide the service. You are responsible for protecting your credentials and promptly notifying LIA if you believe your account has been compromised.", "LIA may reasonably verify identity, contact, payment, or account activity and may temporarily restrict activity to investigate fraud, unauthorized access, payment disputes, abuse, or security concerns."]},
  {title: "4. Participating stores", paragraphs: ["Participating Stores are generally independently owned and are responsible for matters within their control, including products, inventory, descriptions they supply, preparation, packaging, licenses, permits, food safety before proper handoff, and compliance with laws governing their retail operations.", "LIA establishes marketplace quality and fulfillment standards, may investigate complaints, and may take corrective action when appropriate. Nothing in these Terms eliminates any responsibility LIA independently has under applicable law."]},
  {title: "5. Product information, allergies, and dietary requirements", paragraphs: ["LIA and Stores attempt to provide accurate information, but packaging, labels, colors, appearance, manufacturer information, size, ingredients, and other characteristics may change. Images may be representative.", "For allergy, health, dietary, religious, or other important decisions, review the actual label and packaging before consumption or use. Do not rely solely on images, abbreviated descriptions, search results, or previous purchases. LIA content is not medical or nutritional advice."]},
  {title: "6. Product quality and perishables", paragraphs: ["Stores must use reasonable care and are expected to provide products that are fresh, safe, wholesome, accurately represented, and suitable for ordinary use or consumption. Stores may not knowingly use LIA orders to dispose of rotten, spoiled, contaminated, materially damaged, expired, or unacceptable inventory.", "Fresh products naturally vary in appearance, size, ripeness, weight, color, and shape; minor natural variation is not necessarily a defect. Report spoiled, unsafe, expired, materially damaged, or materially incorrect products as soon as reasonably possible. LIA may request photographs or other relevant evidence."]},
  {title: "7. Availability, substitutions, and variable-weight products", paragraphs: ["Displaying a product does not guarantee continued availability. If an item becomes unavailable, the Store or LIA may remove it, contact you, adjust or cancel the item or order, or offer an authorized substitution when that feature is available.", "If substitution preferences or variable-weight products are offered, the checkout experience will explain how replacements, estimates, actual weight, price changes, removals, and refunds are handled. Customers may decline substitutions when that option is available."]},
  {title: "8. Prices and pricing errors", paragraphs: ["Participating Stores generally determine retail product prices, which may differ from another sales channel or the physical Store. The price shown for the LIA transaction governs, subject to disclosed substitutions, variable-weight adjustments, taxes, fees, promotions, or lawful corrections.", "LIA or a Store may correct an obvious technical, pricing, or listing error. If a material error affects an unfulfilled order, LIA may contact you, correct the transaction where permitted, or cancel and refund the affected item or order. LIA will not intentionally charge an amount you did not authorize."]},
  {title: "9. Taxes, fees, and tips", paragraphs: ["Your checkout may include merchandise, estimated taxes, delivery or pickup service fees, delivery fees, tips, regulatory charges, and other amounts disclosed before purchase. Fees may vary by Store, fulfillment method, delivery or pickup location, route distance, order value, promotion, service, delivery zone, demand, or another disclosed factor.", "LIA uses product-level tax classifications and a third-party tax service such as Stripe Tax to calculate applicable sales tax. For delivery, tax location is generally based on the delivery destination; for pickup, it is generally based on the Store location. The tax shown before payment is an estimate. LIA securely recalculates tax when preparing the payment, and the final tax on the order receipt may be higher or lower if items, fulfillment details, locations, registrations, rates, or applicable rules change. LIA collects, reports, and remits taxes when required by applicable law.", "Pickup and delivery may use different service-fee percentages, minimums, or maximums. Pickup orders do not include a delivery fee or driver tip. For delivery orders, a delivery fee is not necessarily a driver gratuity. Unless clearly disclosed otherwise, a driver tip is intended for the driver and is separate from LIA service fees. Review all amounts before confirming payment."]},
  {title: "10. Payment authorization", paragraphs: ["By submitting an order, you authorize LIA and its payment processors to charge the selected payment method for the transaction total presented through checkout, including the final tax calculation and any disclosed adjustments arising from supported substitutions, actual weights, removed items, refunds, or order changes.", "Payment methods may include cards, digital wallets, or other supported methods. Payment information is handled by third-party processors such as Stripe; LIA does not store full payment-card credentials. If saved payment methods become available, processor and customer controls will be presented through the Platform. LIA may decline or cancel a failed, unauthorized, or suspected fraudulent transaction."]},
  {title: "11. Orders, fulfillment selection, and order changes", paragraphs: ["Submitting an order does not guarantee Store acceptance. Orders may pass through statuses such as submitted, payment confirmed, accepted, preparing, ready for pickup, out for delivery, picked up, delivered, cancelled, or refunded. Status names and intermediate steps may vary by fulfillment method.", "Pickup or delivery availability depends on Store settings, customer location, delivery-zone access, pickup-distance limits, operating status, and other marketplace rules. A Store may offer both methods, only one method, or neither method for a particular customer or order.", "Verify the Store, products, quantities, sizes, fulfillment method, address, contact information, instructions, tip, substitution preferences, and payment information before submission. An order cannot ordinarily be converted between pickup and delivery after submission. If you want a different fulfillment method, contact LIA Support; cancellation and a new order may be required, and approval is not guaranteed. Once preparation begins, other changes may also be limited or unavailable."]},
  {title: "12. Cancellations", paragraphs: ["Customers cannot directly cancel an order after submission and must contact LIA Support for assistance. A request is not guaranteed. A Store may cancel only while the order remains pending and before accepting it; a confirmed paid order cancelled by the Store at that stage receives an automatic full refund.", "After acceptance, a Store must contact LIA Support if fulfillment cannot continue. LIA will determine the appropriate action under the published Refund and Cancellation Policy."]},
  {title: "13. Refunds and evidence", paragraphs: ["Full or partial refunds may be appropriate for missing or incorrect items, spoiled or unsafe products, material damage, Store-caused cancellation, significant delivery failures, pickup fulfillment failures attributable to the Store or LIA, duplicate charges, or other circumstances covered by applicable law and the Refund and Cancellation Policy.", "Photo evidence is required for damaged-item and material quality claims, but not merely because an item is missing. LIA may request other reasonably available packaging, descriptions, order, payment, pickup, or delivery information. Approved refunds generally return to the original payment method; banks and payment networks control portions of the processing time."]},
  {title: "14. Refund abuse, chargebacks, and disputes", paragraphs: ["Do not knowingly submit false missing-item, non-delivery, damage, or duplicate claims; manipulate evidence; abuse refund policies; or coordinate fraudulent transactions. LIA may restrict or terminate accounts involved in suspected or confirmed abuse.", "You retain rights provided by financial institutions and applicable law. When practical, contact LIA first so we can investigate. Knowingly submitting a fraudulent payment dispute is prohibited, and LIA may provide transaction and fulfillment records when responding to a dispute."]},
  {title: "15. Delivery information and availability", paragraphs: ["Provide a complete and accurate street address, unit, building details, access instructions, and other information reasonably required to locate the destination. Remain reasonably reachable for access, address, instruction, or safety questions during active delivery.", "LIA is not responsible for failures primarily caused by materially incorrect or incomplete customer information. Failure to respond may affect delivery and refund eligibility."]},
  {title: "16. Estimates and tracking", paragraphs: ["Pickup preparation and delivery times are estimates unless expressly stated otherwise. Store preparation, traffic, weather, driver availability, order volume, roads, distance, emergencies, and other circumstances can affect timing.", "Tracking or readiness information may be delayed or inaccurate because of Store updates, GPS, network, third-party delivery systems, or device limitations. An estimate, readiness message, or tracking display does not guarantee an exact pickup or delivery time."]},
  {title: "17. Delivery handoff and unattended delivery", paragraphs: ["Depending on instructions, an order may be handed to you or another person at the location, left at an authorized place, or completed through another offered method.", "If you authorize unattended delivery, you accept reasonable risks after proper delivery, including theft, weather, temperature change, or animals. Retrieve temperature-sensitive products promptly. This does not excuse improper conduct before delivery is completed."]},
  {title: "18. Failed delivery and delivery providers", paragraphs: ["If delivery cannot be completed because of an incorrect address, inaccessible property, inability to contact you, or another circumstance primarily attributable to you, LIA may reasonably return, cancel, dispose of, or otherwise handle the order; refund eligibility may be affected.", "Delivery may be performed by independent drivers, third-party providers, or other authorized providers using LIA and third-party technology. Treat delivery personnel respectfully and lawfully."]},
  {title: "19. Pickup orders and verification", paragraphs: ["Pickup is available only when enabled for the Store and allowed for the customer under LIA’s location and distance rules. Pickup availability does not create delivery access to that Store, and delivery-zone limits may differ from pickup-distance limits.", "Wait until the Platform notifies you that the order is ready before traveling to the Store. You are responsible for using the displayed Store location, arriving within a reasonable time during applicable Store hours, and following the Store’s pickup instructions. Preparation times are estimates.", "LIA may issue a pickup verification code for the order. Keep the code private until you are physically receiving the order, and provide it only to authorized Store personnel. The Store may view and enter the matching code to confirm handoff. An order may be treated as picked up and completed after successful code verification.", "Contact LIA Support promptly if the Store cannot locate or release a ready order, the order is materially incorrect, or another pickup problem occurs. If you do not collect a prepared order within a reasonable time, especially one containing perishable or temperature-sensitive products, quality and refund eligibility may be affected to the extent permitted by law and the Refund and Cancellation Policy."]},
  {title: "20. Customer conduct and safety", paragraphs: ["You must not threaten, harass, abuse, discriminate, commit fraud, use stolen payment information, submit false claims, manipulate promotions, evade restrictions, access systems without authorization, interfere with accounts, place fictitious orders, abuse support, share a pickup code for an improper purpose, or use the Platform unlawfully.", "Provide a reasonably safe delivery environment, restrain animals when necessary, provide safe access, and behave respectfully toward Store personnel during pickup. Drivers need not enter or complete delivery in apparently dangerous circumstances. Serious threats or dangerous conduct may result in immediate suspension or termination."]},
  {title: "21. Restricted products", paragraphs: ["Products may be prohibited or restricted by LIA or law. Additional requirements will apply if LIA supports regulated or age-restricted products in the future. A listing does not override applicable law. A separate Prohibited Products Policy will be published before it is incorporated into these Terms."]},
  {title: "22. Promotions and credits", paragraphs: ["Promotions may have expiration dates, minimums, Store or geographic limitations, eligibility rules, usage limits, or exclusions. Unless stated otherwise, they have no cash value and may not be sold or transferred. LIA may cancel benefits obtained through fraud or abuse."]},
  {title: "23. Reviews, feedback, and customer content", paragraphs: ["Ratings, reviews, photographs, and feedback must truthfully reflect your experience and must not be unlawful, fraudulent, threatening, defamatory, discriminatory, obscene, or intentionally misleading. LIA may moderate or remove violating content.", "For content you voluntarily submit for publication, you grant LIA a non-exclusive, worldwide, royalty-free license to host, reproduce, display, format, and distribute it as reasonably necessary to operate and promote the Platform. You retain ownership of your original content."]},
  {title: "24. Privacy and location information", paragraphs: ["The LIA Privacy Policy separately describes collection, use, sharing, retention, deletion, and protection of personal information.", "Location and address information may be used to find nearby Stores, determine delivery-zone access and pickup-distance eligibility, calculate driving distance and charges, determine the location used for tax calculation, facilitate fulfillment, show progress, and prevent fraud. LIA will request device permission where required. For supported functionality, you may manually enter an address rather than sharing precise device location."]},
  {title: "25. Communications and push notifications", paragraphs: ["LIA may send transactional account verification, security, order, payment, Store, delivery, refund, and support communications necessary to provide the service. Marketing communications are handled according to applicable law and available preferences.", "You may choose to receive push notifications and control supported categories. Device-level notifications can be disabled through device settings, although this may reduce real-time order-update convenience."]},
  {title: "26. Third-party services and availability", paragraphs: ["LIA relies on providers for payment processing, tax calculation, cloud infrastructure, authentication, mapping, communications, and delivery coordination. Their functionality may also be governed by applicable third-party terms. LIA remains responsible for its own obligations.", "The Platform may be unavailable because of maintenance, updates, outages, provider interruptions, security incidents, emergencies, or circumstances beyond reasonable control. LIA may add, modify, suspend, or discontinue features and may change Store availability, pickup eligibility, delivery areas, payment methods, and fees, with legally required notice for material changes."]},
  {title: "27. Intellectual property and technical restrictions", paragraphs: ["LIA or its licensors own the Platform software, branding, interface, design, logos, text, and technology. You receive a limited, personal, non-exclusive, non-transferable, revocable right to use it lawfully under these Terms.", "You may not unlawfully reverse engineer, circumvent security, scrape using unauthorized automation, introduce malware, gain unauthorized access, interfere with operation, harvest user or Merchant information, or misuse LIA intellectual property."]},
  {title: "28. Suspension and termination", paragraphs: ["LIA may reasonably restrict or suspend an account to investigate fraud, payment or refund abuse, security concerns, dangerous conduct, harassment, Terms violations, or other material risk. Where appropriate, LIA may explain the restriction.", "LIA may terminate accounts for material or repeated violations and may act immediately for fraud, stolen payment methods, serious threats, repeated fraudulent claims, significant security abuse, illegal use, or substantial safety risk. Obligations from earlier transactions survive termination."]},
  {title: "29. Account deletion", paragraphs: ["You may request account deletion through LIA’s account-deletion functionality. LIA will delete or de-identify account-associated personal information as required by law and the Privacy Policy, subject to lawful retention for accounting, taxes, fraud prevention, disputes, chargebacks, legal claims, regulation, and security.", "Deletion is not temporary deactivation and may permanently remove access to profile information, saved addresses and preferences, parts of order history, and other account features. The Platform will explain the review, grace-period, and completion process."]},
  {title: "30. Disclaimers", paragraphs: ["To the maximum extent permitted by law, the Platform is provided on an “as available” basis. LIA does not warrant that every Store, product, or fulfillment method will remain available, pickup or delivery estimates will be exact, images will perfectly represent natural products, the Platform will be uninterrupted, or third-party services will always be available.", "Nothing in these Terms limits consumer rights or warranties that cannot lawfully be excluded."]},
  {title: "31. Merchant products and limitation of liability", paragraphs: ["Participating Merchants are primarily responsible for products they sell and matters within their control, while LIA may assist with complaints, refunds, safety issues, and disputes.", "To the maximum extent permitted by law, LIA will not be liable for indirect, incidental, special, exemplary, punitive, or consequential damages where such damages may lawfully be excluded. Nothing excludes liability that cannot legally be excluded or independently owed by LIA."]},
  {title: "32. Customer responsibility", paragraphs: ["You are responsible for losses resulting from your unlawful, fraudulent, or intentional misuse of the Platform. You are not required to indemnify LIA for losses caused solely by LIA’s unlawful conduct where prohibited by law."]},
  {title: "33. Governing law and dispute resolution", paragraphs: ["Unless mandatory consumer law requires otherwise, Iowa law governs these Terms without regard to conflict-of-law principles. Mandatory consumer protections are not waived.", "Before formal proceedings, you and LIA agree to make a reasonable good-faith effort to resolve disputes through customer support. These Terms contain no mandatory arbitration, class-action waiver, or jury-trial waiver."]},
  {title: "34. Changes to these Terms", paragraphs: ["LIA may update these Terms as services, laws, or operations change. The published version identifies its effective date and last-updated date.", "LIA may notify customers of material changes through the Platform, email, or another reasonable method. When legally required or appropriate because of a material change, LIA may require acceptance of a new version before continued use of account-based services."]},
  {title: "35. Electronic communications and acceptance", paragraphs: ["Contracts, notices, disclosures, and related communications may be provided electronically where permitted by law. Electronic acceptance has the same effect as signing where legally permitted.", "LIA may retain the accepted version, document identifier, authenticated account, and server-recorded date and time of acceptance."]},
  {title: "36. General provisions", paragraphs: ["If a provision is invalid or unenforceable, the remaining provisions continue to the maximum extent permitted. Failure to immediately enforce a provision is not necessarily a waiver.", "These Terms and any policies expressly incorporated after publication constitute the customer agreement concerning Platform use. The Privacy Policy separately governs personal information."]},
  {title: "37. Contact LIA", paragraphs: ["Questions concerning these Terms may be sent to info@liamarketplace.com. LIA’s website is https://www.liamarketplace.com."]},
];
