"use client";

/* Document replacements collect required expiry metadata before upload. */

import { useState } from "react";
import { Upload, X } from "lucide-react";
import type { DriverImageField } from "@/services/driver/driverImageService";

interface Props { label: string; field: Exclude<DriverImageField, "profile-photo">; currentExpirationDate?: string; saving: boolean; onClose: () => void; onSubmit: (input: { file: File; expirationDate: string; issuingState?: string; provider?: string }) => void; }

export function DriverDocumentReplaceModal({ label, field, currentExpirationDate = "", saving, onClose, onSubmit }: Props) {
  const [file, setFile] = useState<File | null>(null); const [expirationDate, setExpirationDate] = useState(currentExpirationDate); const [issuingState, setIssuingState] = useState(""); const [provider, setProvider] = useState("");
  const isLicense = field.startsWith("drivers-license"); const isInsurance = field === "vehicle-insurance";
  return <div className="fixed inset-0 z-50 flex items-end bg-slate-950/45 sm:items-center sm:justify-center sm:p-6" role="dialog" aria-modal="true"><div className="w-full max-w-lg rounded-t-3xl bg-white p-5 shadow-2xl sm:rounded-3xl sm:p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold tracking-wider text-orange-600">DOCUMENT UPDATE</p><h2 className="mt-1 text-xl font-bold">Replace {label}</h2></div><button type="button" onClick={onClose} disabled={saving} className="rounded-full p-2 text-slate-500 hover:bg-slate-100"><X className="h-5 w-5" /></button></div><p className="mt-3 text-sm text-slate-500">Your new document is submitted for administrator review. Your existing approval does not transfer to the replacement.</p><div className="mt-5 space-y-4"><label className="grid cursor-pointer place-items-center gap-2 rounded-2xl border-2 border-dashed border-orange-200 bg-orange-50 p-6 text-center"><Upload className="h-6 w-6 text-orange-600" /><span className="text-sm font-bold text-orange-800">{file ? file.name : "Choose a clear image"}</span><input type="file" className="hidden" accept="image/jpeg,image/png,image/webp,image/avif" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label>{isLicense && <label className="grid gap-1.5 text-sm font-semibold">License issuing state *<input className="rounded-xl border border-slate-200 px-3 py-2.5 uppercase" maxLength={2} placeholder="IA" value={issuingState} onChange={(event) => setIssuingState(event.target.value.toUpperCase())} /></label>}{isInsurance && <label className="grid gap-1.5 text-sm font-semibold">Insurance provider <input className="rounded-xl border border-slate-200 px-3 py-2.5" value={provider} onChange={(event) => setProvider(event.target.value)} /></label>}<label className="grid gap-1.5 text-sm font-semibold">Expiration date *<input className="rounded-xl border border-slate-200 px-3 py-2.5" type="date" value={expirationDate} onChange={(event) => setExpirationDate(event.target.value)} /></label></div><div className="mt-6 flex gap-3"><button type="button" disabled={saving} onClick={onClose} className="flex-1 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold">Cancel</button><button type="button" disabled={saving || !file || !expirationDate || (isLicense && !issuingState)} onClick={() => file && onSubmit({ file, expirationDate, issuingState: isLicense ? issuingState : undefined, provider: isInsurance ? provider : undefined })} className="flex-1 rounded-xl bg-orange-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{saving ? "Submitting…" : "Submit replacement"}</button></div></div></div>;
}
