"use client";

/* Password changes use Firebase Auth re-authentication; no Firestore write occurs. */

import { useState } from "react";
import { EmailAuthProvider, reauthenticateWithCredential, updatePassword } from "firebase/auth";
import { KeyRound } from "lucide-react";
import { auth } from "@/lib/firebase";

export function DriverPasswordSection({ onMessage }: { onMessage: (message: string) => void }) {
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [form, setForm] = useState({ current: "", next: "", confirm: "" });
  const save = async () => { setError(""); if (form.next.length < 8 || !/[A-Z]/.test(form.next) || !/[^A-Za-z0-9]/.test(form.next)) return setError("Use 8+ characters with an uppercase letter and a symbol."); if (form.next !== form.confirm) return setError("New passwords do not match."); const user = auth.currentUser; if (!user?.email) return setError("Sign in again before changing your password."); try { setBusy(true); await reauthenticateWithCredential(user, EmailAuthProvider.credential(user.email, form.current)); await updatePassword(user, form.next); setOpen(false); setForm({ current: "", next: "", confirm: "" }); onMessage("Password updated successfully."); } catch { setError("Your current password is incorrect or the password could not be changed."); } finally { setBusy(false); } };
  return <article className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="rounded-full bg-orange-50 p-3"><KeyRound className="h-5 w-5 text-orange-600" /></div><div><p className="font-bold">Password</p><p className="text-sm text-slate-500">Keep your driver account secure.</p></div></div><button type="button" disabled={busy} onClick={() => { setOpen((value) => !value); setError(""); }} className="text-sm font-bold text-orange-600">{open ? "Cancel" : "Change"}</button></div>{open && <div className="mt-4 grid gap-3"><input className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" type="password" placeholder="Current password" value={form.current} onChange={(event) => setForm({ ...form, current: event.target.value })} /><input className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" type="password" placeholder="New password" value={form.next} onChange={(event) => setForm({ ...form, next: event.target.value })} /><input className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" type="password" placeholder="Confirm new password" value={form.confirm} onChange={(event) => setForm({ ...form, confirm: event.target.value })} />{error && <p className="text-sm text-red-600">{error}</p>}<button type="button" disabled={busy} onClick={() => void save()} className="rounded-xl bg-orange-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60">{busy ? "Updating…" : "Update password"}</button></div>}</article>;
}
